### ISSUE TITLE
memory corruption issues on create

### ISSUE THREAD

**Issue by fpolowood** [hangilc/myclinic-drawer-printer#1]
According to the documentation you are not supposed to free any memory that you pass to a node::Buffer::New, on the other hand, you are supposed to call GlobalUnlock and GlobalFree for the memory allocated by the PrintDlg calls.  So, there is no alternative but to allocate your own buffer and copy the memory used for the Buffer.  This code might be for a later version of V8 using Nan, in case it doesn't compile, you might need to include nan.h

```
@@ -326,16 +326,24 @@ void printerDialog(const v8::FunctionCallbackInfo<Value>& args){
        if( res == S_OK && pd.dwResultAction != PD_RESULT_CANCEL ){
                DEVMODEW *devmodePtr = (DEVMODEW *)GlobalLock(pd.hDevMode);
                int devmodeLength = sizeof(DEVMODEW) + devmodePtr->dmDriverExtra;
-               Local<Object> devmodeBuffer = node::Buffer::New(isolate, (char *)devmodePtr, devmodeLength);
+               char * plocalmode = new char[devmodeLength];
+               memcpy(plocalmode,devmodePtr,devmodeLength);
                GlobalUnlock(pd.hDevMode);
                GlobalFree(pd.hDevMode);
+               Local<Object> devmodeBuffer;
+               node::Buffer::New(isolate, plocalmode, devmodeLength).ToLocal(&devmodeBuffer);
+
                DEVNAMES *devnamesPtr = (DEVNAMES *)GlobalLock(pd.hDevNames);
                WCHAR *outputPtr = ((WCHAR *)devnamesPtr) + devnamesPtr->wOutputOffset;
                int outputLen = wcslen(outputPtr);
                int devnamesLength = (devnamesPtr->wOutputOffset + outputLen + 1) * 2;
-               Local<Object> devnamesBuffer = node::Buffer::New(isolate, (char *)devnamesPtr, devnamesLength);
+               char * plocalnames = new char[devnamesLength];
+               memcpy(plocalnames,devnamesPtr,devnamesLength);
                GlobalUnlock(pd.hDevNames);
                GlobalFree(pd.hDevNames);
+               Local<Object> devnamesBuffer;
+               node::Buffer::New(isolate, plocalnames, devnamesLength).ToLocal(&devnamesBuffer);
+
                Local<Object> obj = Object::New(isolate);
                obj->Set(String::NewFromUtf8(isolate, "devmode"), devmodeBuffer);
                obj->Set(String::NewFromUtf8(isolate, "devnames"), devnamesBuffer);
```

**Comment by hangilc** [comment]
Thank you for the comment.

According to the source code for node_buffer.cc (https://github.com/nodejs/node-v0.x-archive/blob/master/src/node_buffer.cc, line 194), contents of the memory supplied to Buffer::New are copied to the newly allocated memory in Bufer::New. So, I think we don't have to allocate and copy memory as you suggested. Am I missing something?

**Comment by fpolowood** [comment]
That is no longer true.. as you can tell you are quoting from an archive version of node, the current version has the following comment
_Note that when creating a Buffer using Nan::NewBuffer() and an existing char*, it is assumed that the ownership of the pointer is being transferred to the new Buffer for management. When a node::Buffer instance is garbage collected and a FreeCallback has not been specified, data will be disposed of via a call to free(). You must not free the memory space manually once you have created a Buffer in this way._
 https://github.com/nodejs/nan/blob/master/doc/buffers.md

**Comment by fpolowood** [comment]
BTW, that is why I mentioned nan.h.  My code will probably not compile with the old versions of Node (ToLocal for example), but if you include nan.h, then your code should be able to compile in the old version and, also, be future-proof.

**Comment by hangilc** [comment]
This module has been developed against version 0.12 of node.js. It would not compile with other version of node.js. I have revised README to make it explicit.

With version 0.12, `node::Buffer::New(Isolate* isolate, const char* data, size_t length)` copies the content of supplied memory area of memory. (https://github.com/nodejs/node/blob/v0.12.7-release/src/node_buffer.cc#L167 -- lines 167 to 197). 

So, I am sure that current code is valid and has no memory corruption.

When I rewrite the code to suppor more recent versions of node.js, in future, I will examine Buffer::New again remembering your suggestion, or use nan.h ;-)

**Comment by fpolowood** [comment]
I guess, I have to respect that.  But, FYI, the code works perfectly under node 6.5.0 and 6.7.0 as long as those changes are made.  It creates settings, shows settings, selects printer, prints, etc, just fine. So, it might be worth make the change to nan.h and it will be future-proof... just my opinion.  If you want me to help make those changes for 0.12, I will be more than glad to.

**Comment by hangilc** [comment]
I rewrote drawer.cc using Nan API. I confirmed that it works with node.js version 0.12.7 and 6.9.1, and it would probably work with other versions. Usability of this module has been extended.

Thank you fpolowood for your valuable advice!

**Comment by fpolowood** [comment]
:)
